import Head from 'next/head'

import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results results={results}/>
    </div>
  )
}

/* Con esto le decimos al navegador que esta pagina se va a renderizar como Server Side Rendering */
/* La ventaja es que al renderizar mas rapido el SEO de la pagina va ser mucho mas eficiente */
/* Primero se renderiza esta parte que es la del servidor, luego la parte del cliente. */
export async function getServerSideProps(context) {

  const genre = context.query.genre

  const request = await fetch(`https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then(res => res.json())

  return {
    props: {
      results: request.results
    }
  }
}